[package]
name = "wasm-interface-macro-support"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/MGibson1/wasm-interface/tree/main/crates/macro-support"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
