[workspace]

members = [
  "crates/macro",
  "crates/macro-support",
  "crates/package"
]

exclude = ["example"]

[workspace.metadata.release]
allow-branch = ["main"]
consolidate-commits = true
consolidate-pushes = true
